GET http://localhost:4200/products

###
GET http://localhost:4200/products?id=12

###
POST http://localhost:4200/products
Content-Type: application/json

{
    "item": "ravanito",
    "type": "verdura",
    "price": 600,
    "unidad": "kilo"
}

###
PATCH  http://localhost:4200/products?id=12

{
    "price": 350
}

###
DELETE http://localhost:4200/products?id=12

