GET http://localhost:4200/products

###
GET http://localhost:4200/products?id=5

###
POST http://localhost:4200/products
Content-Type: application/json

{
    "item": "choclo",
    "type": "verdura",
    "price": 600,
    "unidad": "kilo"
}

###
PATCH  http://localhost:4200/products?id=2

{
    "price": 1500
}

###
DELETE http://localhost:4200/products?id=11

