GET http://localhost:4200/products

###
GET http://localhost:4200/products?id=12

###
POST http://localhost:4200/products
Content-Type: application/json

{
    "item": "naranja",
    "type": "fruta",
    "price": 1000,
    "unidad": "kilo"
}

###
PATCH  http://localhost:4200/products?id=13

{
    "price": 500
}

###
DELETE http://localhost:4200/products?id=16

